### ISSUE TITLE
Completar Misión 1

### ISSUE THREAD

**Issue by falasias** [yamideus/Pacto_de_HonoRPG#147]
- [x] Asignar misión 1 @falasias
- [x] Completar misión 1 @falasias
- [x] Cambiar la interfaz de misiones @falasias
- [ ] Árbol de honor @falasias
- [x] Modelar selección de personaje @falasias
- [x] Modelar creación de personaje @falasias
- [x] Modelar login @falasias
- [x] Conexion mision BD @Didiazhe

**Comment by yamideus** [comment]
Falto arbol de honor
